services:
  backend:
    build: .
    environment:
      MONGO_URI: mongodb://mongo:27017
    volumes:
      - ./messages:/messages
      - ./config.json:/config.json
  frontend:
    build: ./client
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - backend
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

configs:
  nginx_config:
    file: ./nginx.conf
