version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config.example.json:/config/config.json
    environment:
      MONGO_URI: mongodb://mongo:27017
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
